package ch11;

public class ExceptionExam2 {

	public static void main(String[] args) {
		int[][] array = new int[4][];
		array[0] = new int[] { 1, 2, 3, 4, 5 };
		array[1] = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
		array[2] = null;
		array[3] = new int[51];

		for(int[] arr: array) {
			try {
				printCheck(arr);
			} catch (ArrayLengthOver e) {
				System.out.println(e.getMessage());
			}
		}
		
		

	}

	// throws는 예외 발생시 호출을 한 주체로 떠넘긴다. 다만 main에서 throws를 하면 있으나 없으나 같다.
	public static boolean checkArr(int[] arr) throws ArrayLengthOver {
		if (arr.length > 50) {
			throw new ArrayLengthOver("배열의 길이가 50을 넘어갔습니다.");
		} else {
			return false;
		}
	}

	private static void printCheck(int[] arr) throws ArrayLengthOver {
		if (checkArr(arr)) {
			System.out.println("배열의 길이가 10보다 크거나 같습니다.");
		} else {
			System.out.println("배열의 길이가 10보다 작습니다.");
		}
	}
}
